import { joinPathFragments, Tree } from '@nx/devkit';
import { NEWLINE_SEPARATOR } from '../constants';
import { applySectionChange } from './utils';
import type { DotenvChange, SectionLine } from './types';

const ENV_CONFIG_RELATIVE_PATH = 'lib/config/env.ts';
const SCHEMA_START = '/* schema start */';
const SCHEMA_END = '/* schema end */';
const VARS_START = '/* vars start */';
const VARS_END = '/* vars end */';

export const DEFAULT_ENV_VAR_SCHEMA = 'z.string()';

const SCHEMA_LINE_IDENTIFIER = /^\s*([A-Za-z_][A-Za-z0-9_]*):\s*.+?,?\s*$/;
const VAR_LINE_IDENTIFIER = /^export const ([A-Za-z_][A-Za-z0-9_]*) = process\.env\.\1;$/;

const BASE_ENV_CONFIG = [
  "import { z } from 'zod';",
  '',
  'const envSchema = z.object({',
  "  NODE_ENV: z.enum(['development', 'production']),",
  `  ${SCHEMA_START}`,
  `  ${SCHEMA_END}`,
  '});',
  '',
  'declare global {',
  '  // eslint-disable-next-line @typescript-eslint/no-namespace',
  '  namespace NodeJS {',
  '    interface ProcessEnv extends z.infer<typeof envSchema> {}',
  '  }',
  '}',
  '',
  'export const NODE_ENV = process.env.NODE_ENV;',
  VARS_START,
  VARS_END,
  '',
].join(NEWLINE_SEPARATOR);

function findBlock(lines: string[], start: string, end: string) {
  const startIndex = lines.findIndex((line) => line.trim() === start);
  const endIndex = lines.findIndex((line) => line.trim() === end);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error(
      `env.ts is missing its "${start}" / "${end}" markers — it must be generated by this generator to be updatable.`
    );
  }
  return { startIndex, endIndex };
}

function replaceBlock(
  lines: string[],
  startIndex: number,
  endIndex: number,
  body: string[]
): string[] {
  return [...lines.slice(0, startIndex + 1), ...body, ...lines.slice(endIndex)];
}

function parseKeyedLines(lines: string[], identifier: RegExp): SectionLine[] {
  return lines.map((raw) => {
    const match = raw.match(identifier);
    return match ? { raw, key: match[1] } : { raw };
  });
}

/**
 * [update-env-config]
 * Keeps `lib/config/env.ts`'s zod schema and process.env accessors in sync
 * with the vars a project's .env files declare. `change.set` maps key ->
 * zod schema expression (e.g. `z.string().url()`); the same key is used for
 * the schema property and the exported accessor, per `export const KEY =
 * process.env.KEY`. Idempotent and marker-based, mirroring how .env files
 * themselves are updated in place.
 * January 30th 2026
 */
export function updateEnvConfig(
  tree: Tree,
  sourceRoot: string,
  change: DotenvChange
): void {
  const filePath = joinPathFragments(sourceRoot, ENV_CONFIG_RELATIVE_PATH);
  const text = tree.read(filePath, 'utf-8') ?? BASE_ENV_CONFIG;
  let lines = text.split(NEWLINE_SEPARATOR);

  const schemaBlock = findBlock(lines, SCHEMA_START, SCHEMA_END);
  const schemaLines = applySectionChange(
    parseKeyedLines(lines.slice(schemaBlock.startIndex + 1, schemaBlock.endIndex), SCHEMA_LINE_IDENTIFIER),
    change,
    (key, schema) => `  ${key}: ${schema},`
  );
  lines = replaceBlock(lines, schemaBlock.startIndex, schemaBlock.endIndex, schemaLines.map((line) => line.raw));

  const varsBlock = findBlock(lines, VARS_START, VARS_END);
  const varLines = applySectionChange(
    parseKeyedLines(lines.slice(varsBlock.startIndex + 1, varsBlock.endIndex), VAR_LINE_IDENTIFIER),
    change,
    (key) => `export const ${key} = process.env.${key};`
  );
  lines = replaceBlock(lines, varsBlock.startIndex, varsBlock.endIndex, varLines.map((line) => line.raw));

  tree.write(filePath, lines.join(NEWLINE_SEPARATOR));
}
