import { joinPathFragments, names, Tree, updateJson } from "@nx/devkit";

/**
 * [as-api-key-name]
 * August 2nd 2025, 1:47:53 pm
 */
export function asApiKeyName(name: string) {
  const { constantName } = names(name);
  return constantName.concat('_API_URL');
}

// Fix package.json exports generated by @nx/next libraryGenerator.
// The library generator writes paths with a ./dist/ prefix which is correct
// during development (package root is features/<name>/, build output is
// features/<name>/dist/). However, the published package root IS the dist
// directory, so exports must reference files without the ./dist/ prefix.
export const updatePackageJsonExports = (tree: Tree, projectRoot: string) => {
    const packageJsonPath = joinPathFragments(
        projectRoot,
        'package.json'
    );
    updateJson(tree, packageJsonPath, (json) => {
        json.type = 'module';
        json.main = './index.js';
        json.types = './index.d.ts';
        json.exports = {
            '.': {
                types: './index.d.ts',
                import: './index.js',
                default: './index.js',
            },
            './server': {
                types: './server.d.ts',
                import: './server.js',
                default: './server.js',
            },
            './package.json': './package.json',
        };
        return json;
    });
}