import {
  formatFiles,
  generateFiles,
  type GeneratorCallback,
  joinPathFragments,
  runTasksInSerial,
  Tree,
  updateJson,
} from '@nx/devkit';
import { ClientGeneratorSchema } from './schema';
import { writeWildCardPathToTsConfig } from '../../../lib/ts-config';
import { AXIOS_VERSION, ZOD_VERSION } from '../../../lib/constants/versions';
import {
  initializeProjectGenerator,
  updateDependencies,
} from '../../../lib/utils';
import * as path from 'path';
import { libraryGenerator } from '@nx/next';
import { normalizeClientGenerator } from './utils/normalize';

export async function clientGenerator(
  tree: Tree,
  options: ClientGeneratorSchema
) {
  const normalizedOptions = normalizeClientGenerator(options);
  const tasks: GeneratorCallback[] = [];

  await libraryGenerator(tree, {
    directory: normalizedOptions.directory,
    name: normalizedOptions.name,
    importPath: normalizedOptions.importPath,
    bundler: 'vite',
    publishable: true,
    style: 'tailwind',
    unitTestRunner: 'jest',
    linter: 'eslint',
    component: false,
    skipFormat: true,
    useProjectJson: true,
  });

  // Fix package.json exports generated by @nx/next libraryGenerator.
  // The library generator writes paths with a ./dist/ prefix which is correct
  // during development (package root is clients/<name>/, build output is
  // clients/<name>/dist/). However, the published package root IS the dist
  // directory, so exports must reference files without the ./dist/ prefix.
  const packageJsonPath = joinPathFragments(
    normalizedOptions.projectRoot,
    'package.json'
  );
  updateJson(tree, packageJsonPath, (json) => {
    json.type = 'module';
    json.main = './index.js';
    json.types = './index.d.ts';
    json.exports = {
      '.': {
        types: './index.d.ts',
        import: './index.js',
        default: './index.js',
      },
      './server': {
        types: './server.d.ts',
        import: './server.js',
        default: './server.js',
      },
      './package.json': './package.json',
    };
    return json;
  });

  await initializeProjectGenerator(tree, normalizedOptions, 'client');

  const { sourceRoot, importPath } = normalizedOptions;

  writeWildCardPathToTsConfig(tree, importPath, sourceRoot);
  tree.delete(path.join(sourceRoot, 'lib', 'hello-server.tsx'));

  const dependencies: Record<string, string> = {
    axios: AXIOS_VERSION,
    zod: ZOD_VERSION,
  };

  const devDependencies: Record<string, string> = {};

  tasks.push(updateDependencies(tree, dependencies, devDependencies));

  generateFiles(
    tree,
    path.join(__dirname, 'files', 'src'),
    sourceRoot,
    normalizedOptions
  );

  if (!normalizedOptions.skipFormat) await formatFiles(tree);

  return runTasksInSerial(...tasks);
}

export default clientGenerator;
